name: Check Upstream Release
# Check for new GNU nano releases on the official website and open an issue if a newer version exists

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *' # every day at 12:00 UTC

permissions:
  issues: write

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Run
        run: ./.github/scripts/check-upstream.ps1
        env:
          GH_TOKEN: ${{ github.token }}
