name: Release
# Check for nano-for-windows releases on Anaconda and re-upload to GitHub Releases

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *' # every day at 12:00 UTC

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@a0af7a228712d6121d37aba47adf55c1332c9c2e # v0.9.4
        with:
          run-install: false
      - name: Run
        run: ./.github/scripts/release.ps1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
