name: Release
# Check for nano-for-windows releases on Anaconda and re-upload to GitHub Releases

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *' # every day at 12:00 UTC

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
        with:
          run-install: false
      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y libarchive-tools
      - name: Run
        run: ./.github/scripts/release.ps1
        env:
          GH_TOKEN: ${{ github.token }}
